# Python Numpy Model

# Introduction of Numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import time
import sys

In [4]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

array=np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [5]:
Size=10000000
list1=range(Size)
list2=range(Size)

arr1=np.arange(Size)
arr2=np.arange(Size)

start=time.time()
result=[(x+y) for x,y in zip(list1,list2)]
print("python list take time: ",(time.time()-start)*1000)

start=time.time()
r=arr1+arr2
print("numpy took",(time.time()-start)*1000)


python list take time:  1543.9975261688232
numpy took 15.62952995300293


# Numpy  Basic of array operation

In [6]:
a=np.array([[12,13],[14,15]])
print(a)

print(a.ndim)

print(type(a))

a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,]])
print(a2)

print(a2.ndim)

print("size of item: ",a2.itemsize)

a2.dtype
a2.shape

[[12 13]
 [14 15]]
2
<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
size of item:  4


(4, 3)

In [7]:
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
print(arr)

arr2=np.array([[1,2,3],[4,5,6]],dtype=complex)
arr2

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [8]:
print("Zero Matrix\n",np.zeros((3,4)))
print("Matrix all element is one \n",np.ones((3,4)))


Zero Matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix all element is one 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# np.arange(star,stop,increment)
a=np.arange(1,6,2)
print("arange :\n\n",a)

b=np.linspace(1,6,9)
print("\nLin space function: \n\n",b)

arr=np.array([[1,2,3],[4,5,6],[9,8,7],[3,5,8]])
arr.shape

print("\nreshape the array:\n\n", arr.reshape(3,4))
arr.shape

d=arr.ravel()
print("\nconvert into one row:\n\n",d)

arange :

 [1 3 5]

Lin space function: 

 [1.    1.625 2.25  2.875 3.5   4.125 4.75  5.375 6.   ]

reshape the array:

 [[1 2 3 4]
 [5 6 9 8]
 [7 3 5 8]]

convert into one row:

 [1 2 3 4 5 6 9 8 7 3 5 8]


# Math

In [10]:
arr=np.array([[1,2,3],[4,5,6],[9,8,7],[3,5,8]])
print("manimume value: ",arr.min())
print("position of minimum value:",arr.argmin())
print("maximume value: ",arr.max())
print("position of max value:",arr.argmax())
print("sum all the element: ",arr.sum())
print("sum the column: ",arr.sum(axis=0))
print("sum the row: ",arr.sum(axis=1))
print("squar root of each element: \n",np.sqrt(arr))
print("\nstandard derivation: ",arr.std())
print(arr.argsort())

manimume value:  1
position of minimum value: 0
maximume value:  9
position of max value: 6
sum all the element:  61
sum the column:  [17 20 24]
sum the row:  [ 6 15 24 16]
squar root of each element: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [3.         2.82842712 2.64575131]
 [1.73205081 2.23606798 2.82842712]]

standard derivation:  2.465033242958173
[[0 1 2]
 [0 1 2]
 [2 1 0]
 [0 1 2]]


In [11]:
a=np.array([[1,2],[3,5]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)

print("sum both matrices:\n",a+b)
print("subtrct both matrices:\n",a-b)
print("multiply both matrices:\n",a*b)
print("divide both matrices:\n",a/b)
print("dot product both matrices:\n",a.dot(b))

[[1 2]
 [3 5]]
[[4 5]
 [6 7]]
sum both matrices:
 [[ 5  7]
 [ 9 12]]
subtrct both matrices:
 [[-3 -3]
 [-3 -2]]
multiply both matrices:
 [[ 4 10]
 [18 35]]
divide both matrices:
 [[0.25       0.4       ]
 [0.5        0.71428571]]
dot product both matrices:
 [[16 19]
 [42 50]]


# Index and slicing

In [12]:
a=np.array([1,2,3,4,5,6])
print(a[-5:-1])
print(a[-1])
print(a[0:6])

[2 3 4 5]
6
[1 2 3 4 5 6]


In [13]:
a=np.array([[1,2,3],[9,5,4],[1,4,7]])
print(a)

print("print element of given position: ",a[1,0])

print("print element of given position: ",a[2,2])

print("print 0 position to 2:\n",a[0:2])

print("print element of 0 row and 1 row at position 2:",a[0:2,2])

print("print last row:",a[-1])

print("print last row element from  0 colunm and 2 colunm :",a[-1,0:2])

print(a[:,0:2])

print("\nprint :\n",a[0:2,0:2])


[[1 2 3]
 [9 5 4]
 [1 4 7]]
print element of given position:  9
print element of given position:  7
print 0 position to 2:
 [[1 2 3]
 [9 5 4]]
print element of 0 row and 1 row at position 2: [3 4]
print last row: [1 4 7]
print last row element from  0 colunm and 2 colunm : [1 4]
[[1 2]
 [9 5]
 [1 4]]

print :
 [[1 2]
 [9 5]]


In [14]:
a=np.array([[1,2,3],[9,5,4],[1,4,7]])
for row in a:
    print(row)


for cell in a.flat:
    print(cell)

[1 2 3]
[9 5 4]
[1 4 7]
1
2
3
9
5
4
1
4
7


In [15]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

print("\nput into one :\n",np.vstack((a,b)))

print("\nput into one :\n",np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]

put into one :
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

put into one :
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [16]:
arr=np.arange(30).reshape(2,15)
print(arr)
res=np.hsplit(arr,3)
print("split the array horizutal:\n",res)

print(res[0])

res=np.vsplit(arr,2)
print("split the array vertical:\n",res)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
split the array horizutal:
 [array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
split the array vertical:
 [array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [17]:
a=np.arange(12).reshape(3,4)
print(a)
b=a>4
print(b)

print(a[b])

x=a[b]==-1
print("\n",x)
print(np.where(a>5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]

 [False False False False False False False]
(array([1, 1, 2, 2, 2, 2], dtype=int64), array([2, 3, 0, 1, 2, 3], dtype=int64))


In [18]:
print(np.count_nonzero(a))
print(np.nonzero(a))

11
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


# Iterat array

In [20]:
a=np.arange(12).reshape(3,4)

for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for cell in a.flatten():
        print(cell)
print("\n")      
for cell in np.nditer(a,order="C"):
        print(cell)
print("\n")       
for cell in np.nditer(a,order="F"):
        print(cell)

In [ ]:
for cell in np.nditer(a,order="F",flags=["external_loop"]):
        print(cell)

In [ ]:
np.arange(0,10,4)