In [1]:
import numpy as np

In [8]:
a=np.array([12,3,4,5,6,7])
print(a.ndim)
b=np.array([2.1,3,4,5,6])
b

1


array([2.1, 3. , 4. , 5. , 6. ])

In [11]:
a=np.array([1.1,2.3,3,4,5],dtype="int32")
a

array([1, 2, 3, 4, 5])

In [13]:
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])